version: v1.0
name: Heroku Push

agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

blocks:
  - name: "Build and Push"
    task:
      secrets:
        - name: telegram_bot_env

      prologue:
        commands:
          - checkout
          - cache restore udbot-buildcache
          - curl https://cli-assets.heroku.com/install.sh | sh
          - echo "machine api.heroku.com" >> ~/.netrc
          - echo "  login baalajimaestro@computer4u.com" >> ~/.netrc
          - echo "  password $HEROKU_PASSWORD" >> ~/.netrc
          - echo "machine git.heroku.com" >> ~/.netrc
          - echo "  login baalajimaestro@computer4u.com" >> ~/.netrc
          - echo "  password $HEROKU_PASSWORD" >> ~/.netrc

      jobs:
      - name: Build
        commands:
          - docker build -f Dockerfile.builder -t build-container .
          - docker run -v $(pwd):/build build-container
      epilogue:
        on_pass:
          commands:
            - bash push.sh
            - cache delete udbot-buildcache
            - cache store udbot-buildcache $(pwd)/target
