version: v1.0
name: Heroku Push

agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

blocks:
  - name: "Build and Push"
    task:
      secrets:
        - name: telegram_bot_env

      jobs:
      - name: Build
        commands:
          - curl https://cli-assets.heroku.com/install.sh | sh
          - echo "machine api.heroku.com" >> ~/.netrc
          - echo "  login baalajimaestro@computer4u.com" >> ~/.netrc
          - echo "  password $HEROKU_PASSWORD" >> ~/.netrc
          - echo "machine git.heroku.com" >> ~/.netrc
          - echo "  login baalajimaestro@computer4u.com" >> ~/.netrc
          - echo "  password $HEROKU_PASSWORD" >> ~/.netrc
          - git init
          - git fetch https://github.com/idkwhoiam322/udbot $SEMAPHORE_GIT_SHA
          - git reset --hard FETCH_HEAD
          - git push https://git.heroku.com/idkwhoiam-udbot.git HEAD:master
